# Generated by Django 4.1 on 2022-09-14 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repertoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, null=True)),
                ('Path', models.CharField(max_length=100, null=True)),
                ('test', models.CharField(blank=True, max_length=50, null=True)),
                ('Parent_directory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='listings.repertoire')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FileName', models.CharField(max_length=100)),
                ('Path', models.CharField(max_length=100)),
                ('ImageWidth', models.IntegerField(null=True)),
                ('ImageLength', models.IntegerField(null=True)),
                ('DateTime', models.DateTimeField(null=True)),
                ('GPSLat', models.FloatField(default=43.48883602764395)),
                ('GPSLon', models.FloatField(default=-1.5224230678904995)),
                ('GPSAlt', models.IntegerField(null=True)),
                ('DateTimeDigitized', models.DateTimeField(null=True)),
                ('DateTimeOriginal', models.DateTimeField(null=True)),
                ('DateGPS', models.DateField(null=True)),
                ('ExifImageWidth', models.IntegerField(null=True)),
                ('ExifImageHeight', models.IntegerField(null=True)),
                ('repertoire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.repertoire')),
            ],
        ),
    ]
